### ISSUE TITLE
[Bug]: No 500 catcher registered. Using Rocket default.

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmyBB#91]
### Steps to reproduce

Update instance

### Version

2.0.0

### LemmyBB Logs

```shell
Apr 14 15:28:51 lemmy lemmy_bb[345679]: ERROR: ld.so: object 'libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Apr 14 15:28:51 lemmy lemmy_bb[345679]: [2023-04-14T13:28:51Z WARN  rocket::launch] 🚀 Rocket has launched from http://192.168.100.15:8703
Apr 14 15:28:54 lemmy lemmy_bb[345679]: thread 'rocket-worker-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/template_helpers.rs:168:20
Apr 14 15:28:54 lemmy lemmy_bb[345679]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 14 15:28:54 lemmy lemmy_bb[345679]: [2023-04-14T13:28:54Z ERROR rocket::server::_] Handler community_list panicked.
Apr 14 15:28:54 lemmy lemmy_bb[345679]: [2023-04-14T13:28:54Z WARN  rocket::server::_] A panic is treated as an internal server error.
Apr 14 15:28:54 lemmy lemmy_bb[345679]: [2023-04-14T13:28:54Z WARN  rocket::server::_] No 500 catcher registered. Using Rocket default.
Apr 14 15:28:55 lemmy lemmy_bb[345679]: thread 'rocket-worker-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/template_helpers.rs:168:20
Apr 14 15:28:55 lemmy lemmy_bb[345679]: [2023-04-14T13:28:55Z ERROR rocket::server::_] Handler community_list panicked.
Apr 14 15:28:55 lemmy lemmy_bb[345679]: [2023-04-14T13:28:55Z WARN  rocket::server::_] A panic is treated as an internal server error.
Apr 14 15:28:55 lemmy lemmy_bb[345679]: [2023-04-14T13:28:55Z WARN  rocket::server::_] No 500 catcher registered. Using Rocket default.
Apr 14 15:28:55 lemmy lemmy_bb[345679]: thread 'rocket-worker-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/template_helpers.rs:168:20
Apr 14 15:28:55 lemmy lemmy_bb[345679]: [2023-04-14T13:28:55Z ERROR rocket::server::_] Handler community_list panicked.
Apr 14 15:28:55 lemmy lemmy_bb[345679]: [2023-04-14T13:28:55Z WARN  rocket::server::_] A panic is treated as an internal server error.
Apr 14 15:28:55 lemmy lemmy_bb[345679]: [2023-04-14T13:28:55Z WARN  rocket::server::_] No 500 catcher registered. Using Rocket default.
Apr 14 15:28:56 lemmy lemmy_bb[345679]: [2023-04-14T13:28:56Z WARN  lemmy_bb::error] rate_limit_error
Apr 14 15:28:56 lemmy lemmy_bb[345679]: thread 'rocket-worker-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/template_helpers.rs:168:20
Apr 14 15:28:56 lemmy lemmy_bb[345679]: [2023-04-14T13:28:56Z ERROR rocket::server::_] Handler community_list panicked.
Apr 14 15:28:56 lemmy lemmy_bb[345679]: [2023-04-14T13:28:56Z WARN  rocket::server::_] A panic is treated as an internal server error.
Apr 14 15:28:56 lemmy lemmy_bb[345679]: [2023-04-14T13:28:56Z WARN  rocket::server::_] No 500 catcher registered. Using Rocket default.
Apr 14 15:29:14 lemmy lemmy_bb[345679]: thread 'rocket-worker-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/template_helpers.rs:168:20
Apr 14 15:29:14 lemmy lemmy_bb[345679]: [2023-04-14T13:29:14Z ERROR rocket::server::_] Handler index panicked.
Apr 14 15:29:14 lemmy lemmy_bb[345679]: [2023-04-14T13:29:14Z WARN  rocket::server::_] A panic is treated as an internal server error.
Apr 14 15:29:14 lemmy lemmy_bb[345679]: [2023-04-14T13:29:14Z WARN  rocket::server::_] No 500 catcher registered. Using Rocket default.
```

**Comment by Nutomic** [comment]
This is because of rate limits. They were moved from config file to database in Lemmy 0.17.0, so you need to manually increase "Message rate limit" and "Search rate limit" in lemmy-ui under /admin to a high number.

**Comment by Tealk** [comment]
we should still include in the readme, are there any suggestion values?

**Comment by Nutomic** [comment]
It works if you only make a few requests, but as soon as you reload the page a couple of times the error will show again.

For now I just set them to 9999. My idea for a proper fix was to test how many API requests a page view with lemmy-ui makes and then compare it to requests for lemmybb. Then increase the rate limits by that same factor. You could give that a try if you have time. And if that doesnt give an extremely high number, we could change the defaults in Lemmy so that manual changes arent necessary.

**Comment by Tealk** [comment]
The error ksm with the 2.0 when first loading and now no longer no matter how many times I reload
