### ISSUE TITLE
[Bug]: update for lemmy 0.18.x

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmyBB#99]
### Steps to reproduce

After the Lemmy update 0.18.0 lemmybb could no longer be reached.

### Version

0.18.1-rc.9

### LemmyBB Logs

```shell
Jul 06 12:32:02 lemmy systemd[1]: Started lemmy_bb.service - lemmy_bb.
Jul 06 12:32:02 lemmy lemmy_bb[749691]: ERROR: ld.so: object 'libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Jul 06 12:32:02 lemmy lemmy_bb[749691]: [2023-07-06T10:32:02Z WARN  rocket::launch] 🚀 Rocket has launched from http://192.168.100.15:8703
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z WARN  lemmy_bb::api] Failed to deserialize API response: {"site_view":{"site":{"id":1,"name":"RollenspielMonster","sidebar":"**Regeln & co.**\n\n- [Charta](https://rollenspiel.monster/charta)\n- [Nutzungsbedingungen](https://rollenspiel.monster/terms)\n- [Impressum](https://rollenspiel.monster/imprint)\n- [Datenschutzerklärung](https://rollenspiel.monste>
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z WARN  lemmy_bb::site_fairing] unknown variant `Open`, expected one of `closed`, `requireapplication`, `open` at line 1 column 2295
Jul 06 12:32:36 lemmy lemmy_bb[749691]: thread 'rocket-worker-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/site_fairing.rs:63:53
Jul 06 12:32:36 lemmy lemmy_bb[749691]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z ERROR rocket::server::_] Handler index panicked.
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z WARN  rocket::server::_] A panic is treated as an internal server error.
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z WARN  rocket::server::_] No 500 catcher registered. Using Rocket default.
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z WARN  lemmy_bb::api] Failed to deserialize API response: {"site_view":{"site":{"id":1,"name":"RollenspielMonster","sidebar":"**Regeln & co.**\n\n- [Charta](https://rollenspiel.monster/charta)\n- [Nutzungsbedingungen](https://rollenspiel.monster/terms)\n- [Impressum](https://rollenspiel.monster/imprint)\n- [Datenschutzerklärung](https://rollenspiel.monste>
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z WARN  lemmy_bb::site_fairing] unknown variant `Open`, expected one of `closed`, `requireapplication`, `open` at line 1 column 2295
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z ERROR rocket::server::_] No matching routes for GET /favicon.ico image/avif.
Jul 06 12:32:36 lemmy lemmy_bb[749691]: [2023-07-06T10:32:36Z WARN  rocket::server::_] No 404 catcher registered. Using Rocket default.
Jul 06 12:34:15 lemmy lemmy_bb[749691]: [2023-07-06T10:34:15Z WARN  lemmy_bb::api] Failed to deserialize API response: {"site_view":{"site":{"id":1,"name":"RollenspielMonster","sidebar":"**Regeln & co.**\n\n- [Charta](https://rollenspiel.monster/charta)\n- [Nutzungsbedingungen](https://rollenspiel.monster/terms)\n- [Impressum](https://rollenspiel.monster/imprint)\n- [Datenschutzerklärung](https://rollenspiel.monste>
Jul 06 12:34:15 lemmy lemmy_bb[749691]: [2023-07-06T10:34:15Z WARN  lemmy_bb::site_fairing] unknown variant `Open`, expected one of `closed`, `requireapplication`, `open` at line 1 column 2295
Jul 06 12:34:15 lemmy lemmy_bb[749691]: thread 'rocket-worker-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/site_fairing.rs:63:53
Jul 06 12:34:15 lemmy lemmy_bb[749691]: [2023-07-06T10:34:15Z ERROR rocket::server::_] Handler view_topic panicked.
Jul 06 12:34:15 lemmy lemmy_bb[749691]: [2023-07-06T10:34:15Z WARN  rocket::server::_] A panic is treated as an internal server error.
Jul 06 12:34:15 lemmy lemmy_bb[749691]: [2023-07-06T10:34:15Z WARN  rocket::server::_] No 500 catcher registered. Using Rocket default.
```

**Comment by stnbu** [comment]
I have this issue and I lack a lot of context. I'd be OK with using a particular lemmy and/or lemmyBB version to get compatibility. Or, if it really is a matter of case, can that be worked around?

**Comment by Tealk** [comment]
If you use the following [Docker-compose file](https://github.com/LemmyNet/lemmyBB/blob/main/docker/docker-compose.yml), it should actually run.

**Comment by stnbu** [comment]
@Tealk thanks for the reply. I'm trying to avoid using Docker. I can build and run both binaries (lemmy_server, lemmy_bb) and they both seem to work except for the "API problem" described here. It feels like I'm _close_.

I notice that the linked docker file uses version 0.16.7 for the server and 0.1 for BB. I'll try that combo; easy experiment.

**Comment by Tealk** [comment]
i think 0.17.x was the last supported version

**Comment by stnbu** [comment]
Does [this](https://github.com/LemmyNet/lemmyBB/blob/c7067ede2e37a4bda3dfa48bdf6cb202eb17e392/docker/docker-compose.yml#L31) mean lemmy vers 0.16.7? The numbers attached to the images could be different from the server version (although wouldn't expect that.)

That's the docker-compose.yml you linked me to (which is HEAD of main)

**Comment by Tealk** [comment]
> Does [this](https://github.com/LemmyNet/lemmyBB/blob/c7067ede2e37a4bda3dfa48bdf6cb202eb17e392/docker/docker-compose.yml#L31) mean lemmy vers 0.16.7?

yes

i don't understand what you are trying to tell me with the rest of it

**Comment by stnbu** [comment]
> i think 0.17.x was the last supported version

The docker file you linked indicates 0.16.7 which means its "unsupported".

> i don't understand what you are trying to tell me with the rest of it

I mean: the docker image is "version 0.16.7" but, the version of lemmy_server on that image could be something other than 0.16.7 (but I'd be surprised if it was.)

I'm up for trying all kinds of combos. I "tried" 0.17 before posting here but had problems (probably self-inflicted).

**Comment by Tealk** [comment]
> The docker file you linked indicates 0.16.7 which means its "unsupported".

Everything greater than 0.18.x does not work
Everything equal to less than 0.16.x works
For 0.17.x I am not sure if it worked.

**Comment by stnbu** [comment]
Ah! Ok. I was thinking the wrong "endpoint" and anything before 0.17 was unsupported. All clear now. Thanks.

I am closer. Will try with 0.16.7 for a while (compile time!), "main" of lemmyBB seems most promising. Getting some friendlier errors now.

**Comment by DraconicNEO** [comment]
Are these fixes still applicable for Lemmy 0.19 or will it need to be rewritten for that as well?

**Comment by DraconicNEO** [comment]
I think this should be renamed support for 0.19 since that is the latest version as of late.
